### ISSUE TITLE
Don't publish babel configuration

### ISSUE THREAD

**Issue by gaspoute** [LinusBorg/portal-vue#109]
Hello,

I encountered an error while building my project:
```
./node_modules/portal-vue/dist/portal-vue.js        
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "/home/gaspar/src/ipickupdimona/node_modules/portal-vue/package.json" at 0, attempted to resolve relative to "/home/gaspar/src/ipickupdimona/node_modules/portal-vue"
    at /home/gaspar/src/ipickupdimona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/gaspar/src/ipickupdimona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/gaspar/src/ipickupdimona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/gaspar/src/ipickupdimona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/gaspar/src/ipickupdimona/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/gaspar/src/ipickupdimona/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/gaspar/src/ipickupdimona/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/gaspar/src/ipickupdimona/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/home/gaspar/src/ipickupdimona/node_modules/babel-loader/lib/index.js:175:20)
 @ ./app/app.js 297:0-35
 @ multi ./app/app.js webpack-hot-middleware/client?reload=true
```
I solved it by moving the babel configuration of the `package.json` to a `.babelrc` file and adding it to the `.npmignore`. I think the problem is pretty much the same as that of [v-tooltip](https://github.com/Akryum/v-tooltip/pull/90).

Thanks :-)

**Comment by LinusBorg** [comment]
I'm not sure I understand the source of the problem. are you importing portal-vue from /src instead of one of the built version?

**Comment by gaspoute** [comment]
Indeed, `node_modules` wasn't well ignored :-)
